'use client';

/**
 * Canvas Stream Integration Hook
 * 
 * Connects the Investigation SSE stream to the Studio canvas.
 * Automatically adds elements as they are generated by the investigation.
 */

import { useCallback, useEffect, useRef } from 'react';
import { useStudioStore, CanvasElement, PageMeta } from '../store/useStudioStore';
import type { StreamEvent, Finding, Visualization, Hypothesis } from '@/hooks/useInvestigationStream';

// Extended types for flexible handling
interface LocalVisualization extends Visualization {
  widget?: string;
}

interface LocalStreamEvent {
  type: string;
  event_type?: string;
  phase?: string;
  data: Record<string, any>;
  timestamp: string;
}

// Element ID generator
function generateId(): string {
  return `el-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

// Map finding types to canvas element configurations
function findingToCanvasElement(
  finding: Finding,
  pageIndex: number,
  yOffset: number
): CanvasElement | null {
  const baseElement: Partial<CanvasElement> = {
    id: generateId(),
    x: 40,
    y: yOffset,
    width: 720,
    zIndex: 1,
  };

  switch (finding.type) {
    case 'hypothesis':
    case 'hypothesis_verdict':
      return {
        ...baseElement,
        type: 'component',
        height: 120,
        data: {
          type: 'hypothesis-card',
          module: 'hypothesis',
          componentId: 'HypothesisCard',
          data: {
            id: finding.data.id || finding.data.hypothesis_id,
            statement: finding.data.statement,
            verdict: finding.data.verdict,
            confidence: finding.data.confidence || finding.data.prior_confidence,
          },
        },
      } as CanvasElement;

    case 'overall_confidence':
      return {
        ...baseElement,
        type: 'component',
        height: 150,
        data: {
          type: 'confidence-summary',
          module: 'confidence',
          componentId: 'ConfidenceSummary',
          data: {
            confidence: finding.data.confidence,
            level: finding.data.level,
          },
        },
      } as CanvasElement;

    case 'plan':
      return {
        ...baseElement,
        type: 'text',
        height: 200,
        data: {
          type: 'plan-summary',
          content: `## Investigation Plan\n\n- **Phases**: ${finding.data.phases}\n- **Total Steps**: ${finding.data.total_steps}`,
        },
      } as CanvasElement;

    default:
      // Generic finding card
      if (finding.data.finding) {
        const findingData = finding.data.finding;
        return {
          ...baseElement,
          type: 'component',
          height: 100,
          data: {
            type: 'finding-card',
            module: finding.tool_id || 'unknown',
            componentId: 'FindingCard',
            data: {
              title: findingData.title || finding.type,
              description: findingData.description,
              severity: findingData.severity,
              tool_id: finding.tool_id,
            },
          },
        } as CanvasElement;
      }
      return null;
  }
}

// Map visualization types to canvas elements
function visualizationToCanvasElement(
  viz: LocalVisualization,
  pageIndex: number,
  yOffset: number
): CanvasElement | null {
  const baseElement: Partial<CanvasElement> = {
    id: generateId(),
    x: 40,
    y: yOffset,
    width: 720,
    height: 350,
    zIndex: 1,
  };

  // Map tool_id to component type
  const widgetMap: Record<string, string> = {
    timeline: 'TimelineHeatmap',
    anomaly: 'AnomalyScatter',
    correlation: 'EntityGraph',
    network: 'NetworkFlow',
    crud: 'CRUDOperations',
    depth: 'BlastRadius',
    vault: 'EvidenceSummary',
  };

  const widget = widgetMap[viz.tool_id] || viz.widget || 'GenericChart';

  return {
    ...baseElement,
    type: 'component',
    data: {
      type: 'chart',
      module: viz.tool_id,
      componentId: widget,
      chartType: viz.type,
      data: viz.data,
    },
  } as CanvasElement;
}

interface UseCanvasStreamOptions {
  /** Whether streaming is enabled */
  enabled?: boolean;
  /** Auto-add pages when content overflows */
  autoAddPages?: boolean;
  /** Margin between elements */
  elementMargin?: number;
  /** Page height in mm (A4 = 297mm) */
  pageHeight?: number;
}

export function useCanvasStream(options: UseCanvasStreamOptions = {}) {
  const {
    enabled = true,
    autoAddPages = true,
    elementMargin = 20,
    pageHeight = 1122, // ~297mm at 96dpi
  } = options;

  // Studio store access
  const addElement = useStudioStore((state) => state.addElement);
  const addPage = useStudioStore((state) => state.addPage);
  const pages = useStudioStore((state) => state.pages);
  const setCurrentPage = useStudioStore((state) => state.setCurrentPage);

  // Track current Y position for layout
  const layoutState = useRef({
    currentPage: 0,
    currentY: 60, // Start with top margin
  });

  // Calculate next position and add page if needed
  const getNextPosition = useCallback((elementHeight: number): { pageIndex: number; y: number } => {
    const { currentPage, currentY } = layoutState.current;
    const availableHeight = pageHeight - 60; // Bottom margin

    // Check if element fits on current page
    if (currentY + elementHeight > availableHeight) {
      // Need new page
      if (autoAddPages) {
        const newPageIndex = pages.length;
        addPage();
        layoutState.current = {
          currentPage: newPageIndex,
          currentY: 60,
        };
        return { pageIndex: newPageIndex, y: 60 };
      }
    }

    const position = { pageIndex: currentPage, y: currentY };
    layoutState.current.currentY = currentY + elementHeight + elementMargin;
    return position;
  }, [pages.length, autoAddPages, pageHeight, elementMargin, addPage]);

  // Handle finding event
  const handleFinding = useCallback((finding: Finding) => {
    if (!enabled) return;

    // Estimate height based on type
    const estimatedHeight = finding.type === 'hypothesis' ? 120 : 
                           finding.type === 'plan' ? 200 : 100;
    
    const position = getNextPosition(estimatedHeight);
    const element = findingToCanvasElement(finding, position.pageIndex, position.y);
    
    if (element) {
      addElement(position.pageIndex, element);
      setCurrentPage(position.pageIndex);
    }
  }, [enabled, getNextPosition, addElement, setCurrentPage]);

  // Handle visualization event
  const handleVisualization = useCallback((viz: Visualization) => {
    if (!enabled) return;

    const position = getNextPosition(350);
    const element = visualizationToCanvasElement(viz, position.pageIndex, position.y);
    
    if (element) {
      addElement(position.pageIndex, element);
      setCurrentPage(position.pageIndex);
    }
  }, [enabled, getNextPosition, addElement, setCurrentPage]);

  // Handle text chunk (narrative content)
  const handleTextChunk = useCallback((data: { section: string; content: string; page?: number }) => {
    if (!enabled) return;

    // Estimate height based on content length
    const estimatedHeight = Math.max(100, Math.min(400, data.content.length / 3));
    const position = getNextPosition(estimatedHeight);

    const element: CanvasElement = {
      id: generateId(),
      type: 'text',
      x: 40,
      y: position.y,
      width: 720,
      height: estimatedHeight,
      zIndex: 1,
      data: {
        type: 'narrative',
        section: data.section,
        content: data.content,
        // TipTap-compatible JSON structure
        doc: {
          type: 'doc',
          content: [
            {
              type: 'heading',
              attrs: { level: 2 },
              content: [{ type: 'text', text: data.section }],
            },
            {
              type: 'paragraph',
              content: [{ type: 'text', text: data.content }],
            },
          ],
        },
      },
    };

    addElement(position.pageIndex, element);
    setCurrentPage(position.pageIndex);
  }, [enabled, getNextPosition, addElement, setCurrentPage]);

  // Reset layout state
  const resetLayout = useCallback(() => {
    layoutState.current = {
      currentPage: 0,
      currentY: 60,
    };
  }, []);

  // Process stream event - handles both standard and legacy event formats
  const processEvent = useCallback((event: LocalStreamEvent) => {
    const eventType = event.event_type || event.type;
    
    switch (eventType) {
      case 'finding':
        handleFinding({
          id: event.data.id || `finding-${Date.now()}`,
          type: event.data.type || 'unknown',
          tool_id: event.data.tool_id,
          data: event.data,
          timestamp: event.timestamp,
        });
        break;

      case 'visualization':
        handleVisualization({
          id: event.data.id || `viz-${Date.now()}`,
          tool_id: event.data.tool_id || 'unknown',
          type: event.data.visualization?.type || 'chart',
          widget: event.data.visualization?.widget,
          data: event.data.visualization || event.data,
        } as LocalVisualization);
        break;

      case 'text_chunk':
        handleTextChunk({
          section: event.data.section || 'Content',
          content: event.data.content || '',
          page: event.data.page,
        });
        break;

      case 'phase_start':
        // Add phase header
        const phaseName = event.data.phase || event.phase || 'unknown';
        handleTextChunk({
          section: `Phase: ${String(phaseName).replace(/_/g, ' ').toUpperCase()}`,
          content: '',
        });
        break;
    }
  }, [handleFinding, handleVisualization, handleTextChunk]);

  return {
    processEvent,
    handleFinding,
    handleVisualization,
    handleTextChunk,
    resetLayout,
    layoutState: layoutState.current,
  };
}

export default useCanvasStream;
