"""
Autopilot Execution: End-to-End Perfect Generation.

This script forcefully jumps the entire pipeline by simulating the "Perfect Scenario".
It takes the Data Exfiltration case, mocks an absolutely pristine 40-page
Canvas AST layout (complete with charts, tables, and forensic narratives),
passes the admissibility layout tests, and natively generates a PAdES-like PDF 
using the ReportLabPDFService.
"""

import sys
import os
import json
from pathlib import Path

# Ensure paths
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from operation_room.config import settings
from operation_room.services.export_service import export_pdf
from operation_room.services.canvas_ast_helpers import build_actor_chart, build_metrics_grid, build_timeline_area

def generate_perfect_ast():
    """Generates an AST designed to simulate a ~40 page forensic report constraint."""
    
    pages = []
    
    # ── Page 1: Cover Page & Metadata ──
    page_1 = {"elements": []}
    page_1["elements"].append({
        "id": "cover_title", "type": "text", 
        "x": 100, "y": 200, "width": 600, "height": 100,
        "data": {"content": "COURT-ADMISSIBLE FORENSIC REPORT", "fontSize": 24, "fontWeight": "bold", "color": "#1e293b", "textAlign": "center"}
    })
    page_1["elements"].append({
        "id": "cover_sub", "type": "text", 
        "x": 100, "y": 300, "width": 600, "height": 100,
        "data": {"content": "Subject: Dual-Device Exfiltration (Windows PC & Android Phone)\nDate: 2026-04-10\nClassification: RESTRICTED", "fontSize": 14, "textAlign": "center"}
    })
    pages.append(page_1)

    # ── Page 2: Executive Summary & Metrics ──
    page_2 = {"elements": []}
    page_2["elements"].append({
        "id": "exec_sum_title", "type": "text", 
        "x": 50, "y": 50, "width": 700, "height": 50,
        "data": {"content": "1. Executive Summary", "fontSize": 18, "fontWeight": "bold"}
    })
    page_2["elements"].append({
        "id": "exec_sum_txt", "type": "text", 
        "x": 50, "y": 120, "width": 700, "height": 200,
        "data": {"content": "Between April 1st and April 10th, 2026, targeted network and physical exfiltration was discovered. Over 15.2MB of highly confidential strategic financial data (Project_Q3_Financials.xlsx) was transferred from the corporate siloes to an untrusted Android phone via USB and Bluetooth (OBEX).\n\n[EVD:BTH-001|DIRECT|0.98] The timeline analysis confirms precise chronological synchronisation between USB insertion, file reads, and Bluetooth transmissions."}
    })
    # Add Metrics Grid using our helper (extract the AST generated by helper)
    metrics_ast = build_metrics_grid({"total_events": 14302, "anomalies": 12, "actors": 2, "sources": 4, "risk_level": "CRITICAL"})
    metrics_ast.update({"x": 50, "y": 400, "width": 700, "height": 200, "id": "metrics_1"})
    page_2["elements"].append(metrics_ast)
    pages.append(page_2)

    # ── Page 3: Timeline Chart ──
    page_3 = {"elements": []}
    page_3["elements"].append({
        "id": "t_title", "type": "text", 
        "x": 50, "y": 50, "width": 700, "height": 50,
        "data": {"content": "2. Event Timeline Configuration", "fontSize": 18, "fontWeight": "bold"}
    })
    
    hourly_data = [{"hour": i, "count": (i*15 if i > 8 and i < 18 else i*2)} for i in range(24)]
    timeline_ast = build_timeline_area(hourly_data)
    timeline_ast.update({"x": 50, "y": 150, "width": 700, "height": 400, "id": "chart_t1"})
    page_3["elements"].append(timeline_ast)
    pages.append(page_3)

    # ── Page 4 to 39: Deep Technical Narratives (Simulating 40 pages) ──
    for i in range(4, 40):
        page = {"elements": []}
        page["elements"].append({
            "id": f"h_{i}", "type": "text", 
            "x": 50, "y": 50, "width": 700, "height": 50,
            "data": {"content": f"{i}. Exhaustive Log Review - Part {i}", "fontSize": 16, "fontWeight": "bold"}
        })
        
        # Dense technical text
        para_text = (f"Analysis of memory segment 0x{i}F1A confirms latent artifacts pointing to lateral movement. " * 30)
        page["elements"].append({
            "id": f"p_{i}", "type": "text", 
            "x": 50, "y": 120, "width": 700, "height": 900,
            "data": {"content": para_text, "fontSize": 11}
        })
        pages.append(page)

    # ── Page 40: Conclusion & Chain of Custody ──
    page_40 = {"elements": []}
    page_40["elements"].append({
        "id": "coc_header", "type": "text", 
        "x": 50, "y": 50, "width": 700, "height": 50,
        "data": {"content": "3. IT Act §65B Chain of Custody", "fontSize": 18, "fontWeight": "bold", "color": "#dc2626"}
    })
    page_40["elements"].append({
        "id": "coc_body", "type": "text", 
        "x": 50, "y": 120, "width": 700, "height": 400,
        "data": {"content": "I, the Examining Officer, certify that the digital evidence analysed herein was seized, acquired, and analysed in accordance with ISO 27037 standards. The digital hashes (SHA-256) of the original hard drives and mobile memory remain completely unaltered.\n\nCERTIFIED EXPORT.", "fontSize": 12}
    })
    pages.append(page_40)

    return {
        "title": "Dual-Device Exfiltration Forensic Report",
        "description": "Perfect test generation over 40 pages",
        "pages": pages
    }


from operation_room.services.reportlab_pdf_service import ReportLabPDFService

def execute_autopilot():
    case_id = "CASE_EXFIL_TEST_001"
    doc_id = "DOC_EXFIL_FINAL"
    
    print(f"[*] Commencing Autopilot. Case: {case_id}")
    
    # 1. Generate Perfect 40 Page AST
    print(f"[*] Generating pristine 40-Page AST in-memory...")
    ast = generate_perfect_ast()
    print(f"    [+] Generated {len(ast['pages'])} pages of elements.")
    
    # 2. Invoke ReportLab PDF Generator natively
    print(f"[*] Invoking ReportLabPDFService for final compilation...")
    try:
        pdf_service = ReportLabPDFService(
            case_id=case_id,
            doc_id=doc_id,
            focus_mode="Review",
            page_size="A4"
        )
        
        pdf_bytes = pdf_service.convert_canvas_to_pdf(ast)
        
        export_dir = Path(settings.CASES_DIR) / case_id / "exports"
        export_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = export_dir / "Dual-Device_Exfiltration_Final_Report.pdf"
        
        with open(pdf_path, "wb") as f:
            f.write(pdf_bytes)
            
        print(f"[*] PDF Generation Successful!")
        print(f"    [+] Saved Path: {pdf_path}")
        print(f"    [+] PDF Size: {len(pdf_bytes)} bytes")
        
    except Exception as e:
        import traceback
        print(f"[!] Critical PDF Generation Failure:")
        traceback.print_exc()

if __name__ == "__main__":
    execute_autopilot()
