"""
LLM-Based Hypothesis Generator for Deep Research.

Replaces hardcoded keyword matching with intelligent LLM-powered
hypothesis generation that can handle any forensic scenario.

Features:
- Chain-of-thought reasoning for hypothesis extraction
- Evidence type mapping
- Confidence estimation
- Multi-hypothesis generation
- Null hypothesis inclusion
- Customizable via prompts
"""

import json
import logging
import hashlib
from typing import List, Dict, Any, Optional
from datetime import datetime, timezone
from dataclasses import dataclass, field

from operation_room.services.llm_provider import get_llm

logger = logging.getLogger(__name__)


HYPOTHESIS_GENERATION_SYSTEM_PROMPT = """You are a digital forensics expert assistant specializing in generating testable hypotheses from investigation scenarios.

Your task is to analyze the given scenario and generate comprehensive hypotheses that can be tested against digital evidence.

For each hypothesis, you must:
1. Identify what specific action or activity is suspected
2. Determine what evidence types would prove or disprove it
3. Assign a priority level (high, medium, low)
4. Provide a clear, testable statement

Evidence Types Available:
- usb_connect, usb_disconnect, usb_transfer, usb_device_install
- bluetooth_pair, bluetooth_connect, bluetooth_disconnect, bluetooth_transfer
- email_send, email_receive, email_attach, email_open
- network_connect, network_disconnect, network_data_transfer, network_dns_query
- file_create, file_delete, file_modify, file_copy, file_move, file_read
- auth_logon, auth_logoff, auth_failed, auth_privilege_escalation
- process_start, process_end, process_injection
- system_startup, system_shutdown, system_config_change

Guidelines:
- Generate 3-7 alternative hypotheses based on scenario
- Always include a null hypothesis (H0: No suspicious activity occurred)
- Make hypotheses specific and testable
- Consider temporal aspects (when did it happen?)
- Consider actor/target relationships (who did what to whom?)
- Prioritize hypotheses based on scenario emphasis

Output Format (JSON):
{
  "null_hypothesis": {
    "hypothesis_id": "h0_null",
    "hypothesis_name": "No suspicious activity occurred",
    "description": "All observed activities were within normal operational parameters",
    "required_evidence": [],
    "priority": "low"
  },
  "alternative_hypotheses": [
    {
      "hypothesis_id": "h1_<descriptive_name>",
      "hypothesis_name": "Clear, concise statement",
      "description": "Detailed description of what this hypothesis suggests",
      "required_evidence": ["event_type1", "event_type2", "event_type3"],
      "confidence_threshold": 0.75,
      "priority": "high|medium|low",
      "temporal_constraints": "Optional: when this should have occurred",
      "actor_constraints": "Optional: who should be involved",
      "target_constraints": "Optional: what resources are involved"
    }
  ]
}

Be thorough but focused. Quality over quantity."""


HYPOTHESIS_GENERATION_USER_PROMPT_TEMPLATE = """Analyze this digital forensics investigation scenario and generate testable hypotheses:

SCENARIO:
{scenario}

CONTEXT:
- Case ID: {case_id}
- Investigation Period: {time_range}
- Suspected Entities: {entities}
- Victim Systems: {systems}
- Available Evidence Sources: {evidence_sources}

Generate comprehensive hypotheses that cover:
1. Primary suspected activities mentioned in the scenario
2. Related activities that might have occurred
3. Alternative explanations for observed behavior
4. Null hypothesis (no suspicious activity)

Think step-by-step about what evidence would prove each hypothesis."""


@dataclass
class GeneratedHypothesis:
    """A hypothesis generated by the LLM."""
    hypothesis_id: str
    hypothesis_name: str
    description: str
    required_evidence: List[str]
    confidence_threshold: float = 0.75
    priority: str = "medium"
    temporal_constraints: Optional[str] = None
    actor_constraints: Optional[str] = None
    target_constraints: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "hypothesis_id": self.hypothesis_id,
            "hypothesis_name": self.hypothesis_name,
            "description": self.description,
            "required_evidence": self.required_evidence,
            "confidence_threshold": self.confidence_threshold,
            "priority": self.priority,
            "temporal_constraints": self.temporal_constraints,
            "actor_constraints": self.actor_constraints,
            "target_constraints": self.target_constraints,
            "metadata": self.metadata,
        }


class LLMHypothesisGenerator:
    """
    LLM-powered hypothesis generator.
    
    Uses chain-of-thought reasoning to generate comprehensive,
    testable hypotheses from any forensic investigation scenario.
    """
    
    def __init__(self):
        self.llm = get_llm()
        self.generation_history: List[Dict[str, Any]] = []
    
    async def generate_hypotheses(
        self,
        scenario: str,
        case_id: str = "unknown",
        time_range: Optional[str] = None,
        suspected_entities: Optional[List[str]] = None,
        victim_systems: Optional[List[str]] = None,
        evidence_sources: Optional[List[str]] = None,
        max_hypotheses: int = 7,
    ) -> List[GeneratedHypothesis]:
        """
        Generate hypotheses from scenario using LLM.
        
        Args:
            scenario: Investigation scenario description
            case_id: Case identifier
            time_range: Time period of interest
            suspected_entities: Known suspects/actors
            victim_systems: Systems involved
            evidence_sources: Available evidence types
            max_hypotheses: Maximum number of hypotheses to generate
            
        Returns:
            List of GeneratedHypothesis objects
        """
        # Build context
        context = {
            "case_id": case_id,
            "time_range": time_range or "Not specified",
            "entities": ", ".join(suspected_entities) if suspected_entities else "Not specified",
            "systems": ", ".join(victim_systems) if victim_systems else "Not specified",
            "evidence_sources": ", ".join(evidence_sources) if evidence_sources else "All standard sources",
        }
        
        # Build user prompt
        user_prompt = HYPOTHESIS_GENERATION_USER_PROMPT_TEMPLATE.format(
            scenario=scenario,
            **context
        )
        
        # Call LLM
        try:
            response = await self.llm.generate(
                system_prompt=HYPOTHESIS_GENERATION_SYSTEM_PROMPT,
                user_prompt=user_prompt,
                temperature=0.3,  # Lower temperature for more focused output
                max_tokens=2000,
            )
            
            # Parse response
            hypotheses = self._parse_llm_response(response, scenario, max_hypotheses)
            
            # Store generation history
            self.generation_history.append({
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "scenario": scenario,
                "context": context,
                "hypotheses_generated": len(hypotheses),
                "response_hash": self._hash_string(response),
            })
            
            return hypotheses
            
        except Exception as e:
            logger.error(f"LLM hypothesis generation failed: {e}")
            # Fallback to rule-based generation
            return self._fallback_generation(scenario)
    
    def _parse_llm_response(
        self,
        response: str,
        scenario: str,
        max_hypotheses: int
    ) -> List[GeneratedHypothesis]:
        """Parse LLM JSON response into hypothesis objects."""
        try:
            # Try to extract JSON from response
            json_start = response.find('{')
            json_end = response.rfind('}') + 1
            
            if json_start >= 0 and json_end > json_start:
                json_str = response[json_start:json_end]
                data = json.loads(json_str)
            else:
                raise ValueError("No JSON found in response")
            
            hypotheses = []
            
            # Add null hypothesis
            if "null_hypothesis" in data:
                null_hyp = data["null_hypothesis"]
                hypotheses.append(GeneratedHypothesis(
                    hypothesis_id=null_hyp.get("hypothesis_id", "h0_null"),
                    hypothesis_name=null_hyp.get("hypothesis_name", "No suspicious activity"),
                    description=null_hyp.get("description", ""),
                    required_evidence=null_hyp.get("required_evidence", []),
                    priority="low",
                ))
            
            # Add alternative hypotheses
            if "alternative_hypotheses" in data:
                for i, hyp in enumerate(data["alternative_hypotheses"][:max_hypotheses]):
                    hypotheses.append(GeneratedHypothesis(
                        hypothesis_id=hyp.get("hypothesis_id", f"h{i+1}_generated"),
                        hypothesis_name=hyp.get("hypothesis_name", ""),
                        description=hyp.get("description", ""),
                        required_evidence=hyp.get("required_evidence", []),
                        confidence_threshold=hyp.get("confidence_threshold", 0.75),
                        priority=hyp.get("priority", "medium"),
                        temporal_constraints=hyp.get("temporal_constraints"),
                        actor_constraints=hyp.get("actor_constraints"),
                        target_constraints=hyp.get("target_constraints"),
                    ))
            
            return hypotheses
            
        except Exception as e:
            logger.error(f"Failed to parse LLM response: {e}")
            return self._fallback_generation(scenario)
    
    def _fallback_generation(self, scenario: str) -> List[GeneratedHypothesis]:
        """Fallback rule-based generation if LLM fails."""
        logger.warning("Using fallback rule-based hypothesis generation")
        
        hypotheses = []
        scenario_lower = scenario.lower()
        
        # Null hypothesis
        hypotheses.append(GeneratedHypothesis(
            hypothesis_id="h0_null",
            hypothesis_name="No unauthorized activity occurred",
            description="All observed activities were within normal operational parameters",
            required_evidence=[],
            priority="low"
        ))
        
        # USB hypothesis
        if any(kw in scenario_lower for kw in ["usb", "flash", "thumb drive", "removable"]):
            hypotheses.append(GeneratedHypothesis(
                hypothesis_id="h1_usb_exfiltration",
                hypothesis_name="Data exfiltration via USB device",
                description="Suspect transferred confidential data to USB storage device",
                required_evidence=["usb_connect", "file_copy", "usb_disconnect"],
                confidence_threshold=0.85,
                priority="high"
            ))
        
        # Bluetooth hypothesis
        if any(kw in scenario_lower for kw in ["bluetooth", "wireless", "bt", "pairing"]):
            hypotheses.append(GeneratedHypothesis(
                hypothesis_id="h2_bluetooth_exfiltration",
                hypothesis_name="Data exfiltration via Bluetooth",
                description="Suspect transferred files via Bluetooth to personal device",
                required_evidence=["bluetooth_pair", "bluetooth_transfer"],
                confidence_threshold=0.80,
                priority="high"
            ))
        
        # Email hypothesis
        if any(kw in scenario_lower for kw in ["email", "mail", "attachment", "sent"]):
            hypotheses.append(GeneratedHypothesis(
                hypothesis_id="h3_email_exfiltration",
                hypothesis_name="Data exfiltration via email",
                description="Suspect sent confidential files via email to external account",
                required_evidence=["email_send", "email_attach"],
                confidence_threshold=0.85,
                priority="high"
            ))
        
        # Network hypothesis
        if any(kw in scenario_lower for kw in ["network", "upload", "cloud", "ftp", "transfer"]):
            hypotheses.append(GeneratedHypothesis(
                hypothesis_id="h4_network_exfiltration",
                hypothesis_name="Data exfiltration via network",
                description="Suspect uploaded files to external network location",
                required_evidence=["network_connect", "network_data_transfer"],
                confidence_threshold=0.75,
                priority="medium"
            ))
        
        return hypotheses
    
    def _hash_string(self, text: str) -> str:
        """Compute SHA-256 hash of string."""
        return f"sha256:{hashlib.sha256(text.encode('utf-8')).hexdigest()}"
    
    def get_generation_history(self) -> List[Dict[str, Any]]:
        """Get history of all hypothesis generations."""
        return self.generation_history
    
    async def regenerate_with_feedback(
        self,
        original_scenario: str,
        feedback: str,
        previous_hypotheses: List[GeneratedHypothesis],
    ) -> List[GeneratedHypothesis]:
        """
        Regenerate hypotheses based on user feedback.
        
        Args:
            original_scenario: Original scenario
            feedback: User feedback on previous hypotheses
            previous_hypotheses: Previously generated hypotheses
            
        Returns:
            Refined list of hypotheses
        """
        # Build refinement prompt
        previous_summary = "\n".join([
            f"- {h.hypothesis_id}: {h.hypothesis_name}"
            for h in previous_hypotheses
        ])
        
        refinement_prompt = f"""
I previously generated these hypotheses:

{previous_summary}

The investigator provided this feedback:
{feedback}

Please regenerate the hypotheses taking this feedback into account.
Keep what was good, improve what needs work, and add anything missing.

Original scenario:
{original_scenario}
"""
        
        response = await self.llm.generate(
            system_prompt=HYPOTHESIS_GENERATION_SYSTEM_PROMPT,
            user_prompt=refinement_prompt,
            temperature=0.3,
            max_tokens=2000,
        )
        
        return self._parse_llm_response(response, original_scenario, max_hypotheses=10)


# Global instance
_hypothesis_generator = None


def get_hypothesis_generator() -> LLMHypothesisGenerator:
    """Get or create global hypothesis generator instance."""
    global _hypothesis_generator
    if _hypothesis_generator is None:
        _hypothesis_generator = LLMHypothesisGenerator()
    return _hypothesis_generator


async def generate_hypotheses_from_scenario(
    scenario: str,
    case_id: str = "unknown",
    **kwargs
) -> List[Dict[str, Any]]:
    """
    Main function to generate hypotheses from scenario.
    
    This replaces the hardcoded keyword matching with intelligent LLM-based generation.
    
    Args:
        scenario: Investigation scenario description
        case_id: Case identifier
        **kwargs: Additional context (time_range, entities, systems, etc.)
        
    Returns:
        List of hypothesis dictionaries compatible with existing code
    """
    generator = get_hypothesis_generator()
    
    hypotheses = await generator.generate_hypotheses(
        scenario=scenario,
        case_id=case_id,
        **kwargs
    )
    
    # Convert to dict format for compatibility
    return [h.to_dict() for h in hypotheses]
